import "./global.css";
import { Roboto_Mono, Noto_Sans_KR } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});

const noto_sans = Noto_Sans_KR({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
  weight: "100",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="className={`${noto_sans.variable} ${roboto_mono.variable}`}"
    >
      <body>{children}</body>
    </html>
  );
}
